git:
  depth: false

language: java

env:
  global:
    - LC_ALL=en_US.UTF-8
    - GRADLE_OPTS=-Dorg.gradle.parallel=false
    - JAVA8_JDK=https://cdn.azul.com/zulu/bin/zulu8.40.0.25-ca-jdk8.0.222-linux_x64.tar.gz
    - JAVA11_JDK=https://cdn.azul.com/zulu/bin/zulu11.33.15-ca-jdk11.0.4-linux_x64.tar.gz

matrix:
  include:
    - name: "OpenJDK8"
    - name: "OpenJDK11"
      install:
        - "source install-jdk.sh --url $JAVA11_JDK"
  allow_failures:
    - env: ALLOW_FAILURE=true

before_install:
  - "unset _JAVA_OPTIONS"
  - "curl -O -L --retry 3 https://github.com/sormuras/bach/raw/master/install-jdk.sh"

install:
  - "source install-jdk.sh --url $JAVA8_JDK"

before_script:
  - "./mvnw --version"

script:
  - "./mvnw --no-transfer-progress clean install"
